# Generated by: Cerebras (llm_router) - cleaned up
# Handles complex analysis requests via Free Fleet

from pathlib import Path
from core import llm_router

def handle_analysis(deterministic_tool):
    """Route analysis requests to Free Fleet."""
    if "analysis" not in deterministic_tool:
        return None

    analysis_type = deterministic_tool["analysis"]

    # Build prompt based on analysis type
    if "target" in deterministic_tool:
        # File-based analysis (analyze/summarize file)
        filename = deterministic_tool["target"]
        try:
            content = Path(filename).read_text(encoding='utf-8')
            if analysis_type == "analyze":
                prompt = f"Analyze this code file ({filename}):\n\n{content}\n\nProvide a concise analysis covering: purpose, key functions, patterns used, and potential issues."
            elif analysis_type == "summarize":
                prompt = f"Summarize this file ({filename}):\n\n{content}\n\nProvide a brief summary of what it does."
            else:
                prompt = f"{analysis_type.title()}: {content}"
        except Exception as e:
            return {
                "response": f"Error reading {filename}: {str(e)}",
                "tool_calls": [],
                "provider": "error",
                "tier": "free"
            }
    elif "topic" in deterministic_tool:
        # Topic-based analysis (explain/summarize concept)
        topic = deterministic_tool["topic"]
        if analysis_type == "explain":
            prompt = f"Explain: {topic}\n\nProvide a clear, concise explanation."
        elif analysis_type == "summarize":
            prompt = f"Summarize: {topic}"
        else:
            prompt = f"{analysis_type.title()}: {topic}"
    else:
        return {
            "response": f"Unable to determine what to {analysis_type}.",
            "tool_calls": [],
            "provider": "error",
            "tier": "free"
        }

    # Route to Free Fleet
    try:
        response = llm_router.ask(prompt, preferred_tier="free")
        if response:
            return {
                "response": response.content.strip(),
                "tool_calls": [],
                "provider": response.provider,
                "tier": response.tier
            }
        else:
            return {
                "response": "Free Fleet unavailable. All providers failed.",
                "tool_calls": [],
                "provider": "none",
                "tier": "free"
            }
    except Exception as e:
        return {
            "response": f"Free Fleet error: {str(e)}",
            "tool_calls": [],
            "provider": "error",
            "tier": "free"
        }
