# Generated by: Ollama Minimax (llm_router)
# Generated by: composio (llm_router)
"""Composio Integration Provider for Kart Tool Engine. 984+ integrations."""

import json
import requests
from pathlib import Path
from typing import Dict, Any, Optional

COMPOSIO_BASE = "https://backend.composio.dev/api/v3"
CREDENTIALS_PATH = Path("C:/Users/Sean/Documents/GitHub/Willow/credentials.json")

_api_key: Optional[str] = None
_connections: Optional[Dict] = None


def _load_credentials() -> Dict:
    with open(CREDENTIALS_PATH, "r", encoding="utf-8") as f:
        return json.load(f)


def _get_api_key() -> str:
    global _api_key
    if _api_key is None:
        creds = _load_credentials()
        key = creds.get("COMPOSIO_API_KEY")
        if not key:
            raise ValueError("Missing COMPOSIO_API_KEY in credentials")
        _api_key = key
    return _api_key


def _get_connections() -> Dict:
    global _connections
    if _connections is None:
        creds = _load_credentials()
        conns = creds.get("COMPOSIO_CONNECTIONS")
        if conns is None:
            _connections = {
                "github": {
                    "connected_account_id": "ca_mBZTAcH5KF5T",
                    "entity_id": "sweet-pea-rudi19"
                }
            }
        else:
            _connections = conns
    return _connections


def _headers() -> Dict:
    return {
        "x-api-key": _get_api_key(),
        "Content-Type": "application/json"
    }


def execute_action(action_slug: str, arguments: Dict[str, Any], toolkit_slug: Optional[str] = None) -> Dict:
    if toolkit_slug is None:
        prefix = action_slug.split("_")[0]
        toolkit_slug = prefix.lower()

    connections = _get_connections()
    conn = connections.get(toolkit_slug)
    if not conn:
        return {
            "success": False,
            "error": f"No connection found for toolkit {toolkit_slug}",
            "action": action_slug,
            "provider": "composio"
        }

    url = f"{COMPOSIO_BASE}/tools/execute/{action_slug}"
    payload = {
        "connected_account_id": conn["connected_account_id"],
        "entity_id": conn["entity_id"],
        "arguments": arguments
    }

    try:
        response = requests.post(url, headers=_headers(), json=payload, timeout=30)
        response.raise_for_status()
        data = response.json()
        return {
            "success": True,
            "result": data,
            "action": action_slug,
            "provider": "composio"
        }
    except requests.RequestException as e:
        return {
            "success": False,
            "error": str(e),
            "action": action_slug,
            "provider": "composio"
        }


def list_actions(toolkit_slug: str, limit: int = 20) -> Dict:
    url = f"{COMPOSIO_BASE}/tools"
    params = {
        "toolkit": toolkit_slug,
        "limit": limit
    }
    try:
        response = requests.get(url, headers=_headers(), params=params, timeout=30)
        response.raise_for_status()
        return response.json()
    except requests.RequestException as e:
        return {"error": str(e)}


def list_connected_toolkits() -> Dict:
    connections = _get_connections()
    return {
        "success": True,
        "toolkits": list(connections.keys())
    }


def github_create_issue(repo: str, title: str, body: str = "") -> Dict:
    if "/" not in repo:
        return {"success": False, "error": "Repo must be in 'owner/repo' format", "provider": "composio"}
    owner, repo_name = repo.split("/", 1)
    arguments = {
        "owner": owner,
        "repo": repo_name,
        "title": title,
        "body": body
    }
    return execute_action("GITHUB_CREATE_AN_ISSUE", arguments)


def github_list_repos() -> Dict:
    return execute_action("GITHUB_ACTIVITY_LIST_REPO_S_STARRED_BY_AUTHENTICATED_USER", {})


def github_create_pr(repo: str, title: str, head: str, base: str, body: str = "") -> Dict:
    if "/" not in repo:
        return {"success": False, "error": "Repo must be in 'owner/repo' format", "provider": "composio"}
    owner, repo_name = repo.split("/", 1)
    arguments = {
        "owner": owner,
        "repo": repo_name,
        "title": title,
        "head": head,
        "base": base,
        "body": body
    }
    return execute_action("GITHUB_PULLS_CREATE", arguments)