# Generated by: Cerebras (llm_router)
# Refined by: Claude Code (hash logic + extension handling fixes)
"""
Filename Sanitization for AIOS

Prevents "Filename too long" errors by truncating and hashing overly descriptive names.
Uses Base-17 encoding for compact, human-readable hashes.
"""

import os
import re
import hashlib


# Base-17 alphabet (from cli/base17.py)
BASE17_ALPHABET = "0123456789ACEHKLNRTXZ"


def _hash_to_base17(text, length=5):
    """Convert text to Base-17 hash."""
    hash_bytes = hashlib.md5(text.encode('utf-8')).digest()
    hash_int = int.from_bytes(hash_bytes[:4], 'big')
    
    chars = []
    for _ in range(length):
        hash_int, rem = divmod(hash_int, 17)
        chars.append(BASE17_ALPHABET[rem])
    
    return "".join(reversed(chars))


def sanitize_filename(filename, max_length=80):
    """
    Sanitize filename for safe filesystem use.
    
    Args:
        filename: Original filename (may be very long or contain bad chars)
        max_length: Maximum filename length (default 80 chars)
    
    Returns:
        Sanitized filename (safe for git, Windows, macOS, Linux)
    
    Examples:
        >>> sanitize_filename("Based on the context... memory banks.pdf")
        'Based_on_the_context_available_to_me_right_now_which_includes-7KE2N.pdf'
        
        >>> sanitize_filename("file:///test.txt")
        'file___test.txt'
    """
    if not filename or filename.isspace():
        return f"unnamed-{_hash_to_base17('empty')}.txt"
    
    # Separate filename from extension
    name, ext = os.path.splitext(filename)
    
    # Remove problematic characters (replace with underscore)
    # Problematic: / \ : * ? " < > |
    name = re.sub(r'[/\:*?"<>|]', '_', name)
    
    # Remove multiple consecutive underscores
    name = re.sub(r'_{2,}', '_', name)
    
    # Trim whitespace
    name = name.strip('_').strip()
    
    # If name is empty after sanitization
    if not name:
        name = f"unnamed-{_hash_to_base17(filename)}"
    
    # Truncate if needed (leave room for -HASH + extension)
    max_name_length = max_length - len(ext) - 6  # -6 for "-XXXXX"
    
    if len(name) > max_name_length:
        original_hash = _hash_to_base17(filename, length=5)
        name = name[:max_name_length] + '-' + original_hash
    
    return name + ext


# Quick test
if __name__ == "__main__":
    test_cases = [
        "Based on the context available to me right now (which includes a summary of our past year and our immediate session today), here is the Raw Data Extraction of what is confirmed in my memory banks.pdf",
        "file:///test.txt",
        "normal_file.doc",
        "  .pdf",
        "no<>bad|chars?.txt"
    ]
    
    for test in test_cases:
        result = sanitize_filename(test)
        print(f"{len(test):3d} -> {len(result):2d}: {result}")
