# Generated by: Ollama Minimax (llm_router)
import os, glob as g
from core.db import get_connection
from core import user_lattice, knowledge


def run_startup(username: str) -> dict:
    steps, nodes, ingested, errors = 0, 0, 0, []

    DIYNAMIC = r"C:\Users\Sean\Documents\GitHub\die-namic-system"
    WILLOW = r"C:\Users\Sean\Documents\GitHub\Willow"
    AIOS = r"C:\Users\Sean\Documents\GitHub\aios-minimal"
    INDEX_DB = os.path.join(DIYNAMIC, ".index.db")
    SESSION_DB = os.path.join(DIYNAMIC, "continuity_ring", ".session_index.db")

    # STEP 1: Read INDEX.md -> infrastructure lattice node
    try:
        index_md_path = os.path.join(DIYNAMIC, "INDEX.md")
        with open(index_md_path, "r", encoding="utf-8") as f:
            content = f.read()
        user_lattice.store(username, domain="infrastructure", depth=13, temporal="established", content=content[:500], source="kart_startup")
        nodes += 1
        steps += 1
    except Exception as e:
        errors.append(f"Step 1 failed: {str(e)}")

    # STEP 2: Query .index.db recent 20 files -> codebase lattice node
    try:
        conn = get_connection(INDEX_DB)
        cursor = conn.cursor()
        cursor.execute("SELECT name FROM files ORDER BY modified DESC LIMIT 20")
        recent_files = cursor.fetchall()
        conn.close()
        content = "\n".join([f[0] for f in recent_files])
        user_lattice.store(username, domain="codebase", depth=14, temporal="recent", content=content, source="kart_startup")
        nodes += 1
        steps += 1
    except Exception as e:
        errors.append(f"Step 2 failed: {str(e)}")

    # STEP 3: Query session_index.db seeds (last 3) -> sessions lattice nodes
    try:
        conn = get_connection(SESSION_DB)
        cursor = conn.cursor()
        cursor.execute("SELECT title, content FROM seeds ORDER BY date DESC LIMIT 3")
        seeds = cursor.fetchall()
        conn.close()
        for seed in seeds:
            node_content = (seed[0] or "") + ": " + (seed[1] or "")[:200]
            user_lattice.store(username, domain="sessions", depth=11, temporal="archived", content=node_content[:400], source="kart_startup")
            nodes += 1
        steps += 1
    except Exception as e:
        errors.append(f"Step 3 failed: {str(e)}")

    # STEP 4: Glob SEED_PACKET*.md newest 3 from governance/seeds/ -> history lattice nodes
    try:
        patterns = [os.path.join(DIYNAMIC, "governance", "seeds", "SEED_PACKET*.md"), os.path.join(DIYNAMIC, "archive", "seeds", "SEED_PACKET*.md"), os.path.join(DIYNAMIC, "governance", "SEED_PACKET*.md")]
        found = []
        for pat in patterns:
            found.extend(g.glob(pat))
        all_seeds = sorted(set(found), key=os.path.getmtime, reverse=True)[:3]
        for seed_path in all_seeds:
            with open(seed_path, "r", encoding="utf-8") as f:
                content = f.read()
            user_lattice.store(username, domain="history", depth=7, temporal="archived", content=content, source="kart_startup")
            nodes += 1
        steps += 1
    except Exception as e:
        errors.append(f"Step 4 failed: {str(e)}")

    # STEP 5: Ingest INDEX.md + README.md from DIYNAMIC, WILLOW, AIOS into knowledge DB
    repos = [DIYNAMIC, WILLOW, AIOS]
    files_to_ingest = ["INDEX.md", "README.md"]
    try:
        import hashlib
        for repo in repos:
            for fname in files_to_ingest:
                file_path = os.path.join(repo, fname)
                if not os.path.exists(file_path):
                    continue
                with open(file_path, encoding="utf-8", errors="replace") as _f:
                    text = _f.read()
                fhash = hashlib.md5(text.encode()).hexdigest()
                loam.ingest_file_knowledge(username, fname, fhash, "readme", text[:4000], "kart_startup")
                ingested += 1
        steps += 1
    except Exception as e:
        errors.append(f"Step 5 failed: {str(e)}")

    return {"steps_completed": steps, "lattice_nodes": nodes, "knowledge_ingested": ingested, "errors": errors}
